### ISSUE TITLE
README. md

### ISSUE THREAD

**Issue by Adarsh-jaiss** [sirilalithaadapa/Notes-CSE-IT#2]
@sirilalithaadapa 

**I would like to draw your attention towards your README. md files because you haven't mentioned anything in that. As you know that readme file is an introductory file that that  contains all the information about the projects. So, I want to work on that.  I will need some help from you as well while adding information in that readme file.**

-- `` I'll be waiting for you reply. ``

**Comment by sirilalithaadapa** [comment]
Yeah sure!

**Comment by Adarsh-jaiss** [comment]
😄
